title: Multicellular Systems and Engineering Lab
description: "This is a code repository for the manuscript titled: "MAPPER: A new image analysis pipeline unmasks differential regulation of Drosophila wing features."
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman